version: "3.8"

volumes:
  pgdata:

services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d/
  django:
    build:
      context: ./
    container_name: quokka-backend
    ports:
      - 8000:8000
    volumes:
       - /Users/jeehoon/workplace/project/quokkaletter/backend:/backend
